services:
  - type: web
    runtime: static
    name: ember-todo-test
    rootDir: apps/ember-todo-test/
    buildCommand: pnpm build
    staticPublishPath: dist/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    runtime: static
    name: svelte-todo 
    rootDir: apps/todo-svelte/
    buildCommand: pnpm build
    staticPublishPath: build/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: PUBLIC_EMBEDDED_APP_HOST
        fromService:
          type: web
          name: ember-todo-test
          property: host

envVarGroups:
  - name: settings
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
